### ISSUE TITLE
Push notification and doorbell incompatible

### ISSUE THREAD

**Issue by albertodig** [Samfox2/homebridge-doorbell#1]
hi all, i have the following 2 problems.. someone can help me?
-I'm using doorbell plugin but seems that doorbell notification arrives only to my smartphone and not to the other people that are sharing my home. it is a common problem?

-Doorbell seems be incompatible accessory with IOS10 (ITALY). Possible? Anyway i'm able to receive notification on my iphone and open live view cam.

![img_1185](https://cloud.githubusercontent.com/assets/23417999/20237977/1da6615e-a8e1-11e6-9974-a4ee3f209840.PNG)
![img_1186](https://cloud.githubusercontent.com/assets/23417999/20237978/1da918fe-a8e1-11e6-9db4-80dc49ec7566.PNG)

Very intresting project, thank you!!

**Comment by Samfox2** [comment]
Hi, at this time this is just a basic demo of a homrkit doorbell. Although home app is reporting "not compatible" messages are still send to icloud connected devices if there is a camera in the same room.

**Comment by michaeljanich** [comment]
I've put the doorbell onto a switch (with wiringpi-node) and I also get "Unsupported" in "Home" and I get no message, that someone rang the doorbell. Will I only get a (photo) message with a camera?

What is supposed to happen? Should I not get a message saying "someone is at the door"???

I'm running iOS11.1

Here some code fragments:

```
function ProgrammableSwitch(accesory, log, config) {
    this.log = log;
    this.pin = config.pin;
    this.inverted = config.inverted || false;
    
    this.service = new Service.Doorbell(config.name);
    this.service
        .getCharacteristic(Characteristic.ProgrammableSwitchEvent)
        .on('get', this.getState.bind(this));
    
    wpi.pinMode(this.pin, wpi.INPUT);
    //wpi.pullUpDnControl(this.pin, wpi.PUD_DOWN);
    wpi.wiringPiISR(this.pin, wpi.INT_EDGE_BOTH, this.stateChange.bind(this));
    
    accesory.addService(this.service);
}

ProgrammableSwitch.prototype = { 	
    stateChange: function(delta) {
 	var state = wpi.digitalRead(this.pin);
 	if (this.inverted)
 	    state = !state;
        if (state) {
	    this.service.setCharacteristic(Characteristic.ProgrammableSwitchEvent, Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS);
	}
    }
}

```

**Comment by Samfox2** [comment]
API was changed so that doorbell service is not working as single service anymore. You have to change the doorbell service to motionsensor or use my video doorbell plugin (based on ffmpeg plugin):  https://github.com/Samfox2/homebridge-videodoorbell
