### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by brownad** [Samfox2/homebridge-doorbell#5]
After a few reinstalls and iOS updates I can't get this plugin nor the fork I made to work.

Does it still work for you on latest iOS and on uninstall / reinstall or is it over for now until later?

**Comment by Samfox2** [comment]
Doesn't  work for me after the last iOS update :-(

**Comment by brownad** [comment]
Sucks...

I keep on hearing that combining with a camera or even another accessory is the way to go but it's no so clear how to achieve this.

I've opted to swap out for motion sensor to act as a switch on my fork - testing it later it's not going to be as rich but least it should work
