### ISSUE TITLE
Trigger doorbell from automation part of ios app

### ISSUE THREAD

**Issue by haavardNO** [Samfox2/homebridge-doorbell#6]
Is it possible to add the possibility to trigger the doorbell from the automation part of the home app?
If that was the case I could trigger the doorbell when a switch changes state. And by that trigger the door notification.

**Comment by brownad** [comment]
I don't think the doorbell works in the way you might expect.

Doorbell needs to be a service with another plugin, like a motion sensor.

You might be better off using a motion sensor instead of the doorbell.

**Comment by haavardNO** [comment]
I have several motion sensors already connected with zwave and indigo. And I have  sensor connected to my doorbell. But I don't see a way to trigger the rich notification without a doorbell addition to homebridge. Or am I missing something?

Sendt fra min iPhone

> Den 18. apr. 2017 kl. 15.11 skrev brownad <notifications@github.com>:
> 
> I don't think the doorbell works in the way you might expect.
> 
> Doorbell needs to be a service with another plugin, like a motion sensor.
> 
> You might be better off using a motion sensor instead of the doorbell.
> 
> Sent from my iPhone
>

**Comment by brownad** [comment]
Motion sensors also have notifications - I get updates from the doorbird camera as I placed it in the same room as the camera stream.  Just switch it on in iOS to show notifications on your motion sensor.

**Comment by brownad** [comment]
I did this with my doorbird, have a look at my repo to see more

**Comment by haavardNO** [comment]
Can I use the doorbird plugin when I dont have a doorbird?

**Comment by brownad** [comment]
Doorbird nope it's tightly coupled to their apis 

But you can use this sample plugin to see what works doesn't work.

As I understand you have to add a doorbell service to another service to make the doorbell work e.g. A camera

**Comment by Samfox2** [comment]
Ok, I borrowed the camera-ffmpeg code from @KhaosT and added the doorbell service and a basic webserver to trigger it from „outside“. The device is recognized in home app and you can receive notifications - but the code is really messy.
Maybe somebody has time to implement it as optional service class into the camera-ffmpeg plugin as it would be useable with many video doorbell setups :-)

https://github.com/Samfox2/homebridge-videodoorbell

**Comment by Samfox2** [comment]
Does work now in homebridge-videodoorbell
