### ISSUE TITLE
Doorbell Not Supported in Home App

### ISSUE THREAD

**Issue by arachnetech** [Samfox2/homebridge-doorbell#7]
When I run this with the sample configuration, the Home app simply shows 'Not Supported' and there is no notification when the 'Ding Dong' test event fires.

Reading the comments to the other issues, it seems that Homekit can't handle a simple doorbell that doesn't also include a camera and a motion sensor. Is that correct? I only have a simple doorbell (but modified with an ESP8266)! Is there any way that I can add it to Homekit as a Doorbell? (I currently have it set up as a motion sensor, which is somewhat unsatisfactory.)

(I'm using iOS 10.3.2. I've also tested on the iOS 11 Betas with the same results.)

Thanks in advance for any help anyone can give me.

David

**Comment by Samfox2** [comment]
No,it's not working anymore. The doorbell service has to be attached to a video doorbell. If you don't have a cam you also could switch to a motion sensor service which supports notifications.
