### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by toshibochan** [Samfox2/homebridge-doorbell#8]
pi@toshiboPI33:~ $ sudo npm install -g git+https://github.com/Samfox2/homebridge-doorbell.git
npm ERR! code 128
npm ERR! Command failed: git clone --mirror -q https://github.com/Samfox2/homebridge-doorbell.git /root/.npm/_cacache/tmp/git-clone-eda28104/.git
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-eda28104/.git'
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-23T18_46_00_057Z-debug.log

im not able to install.

**Comment by toshibochan** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'git+https://github.com/Samfox2/homebridge-doorbell.git' ]
2 info using npm@6.14.8
3 info using node@v10.22.0
4 verbose npm-session 10df30da31b81568
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/Samfox2/homebridge-doorbell.git Command failed: git clone --mirror -q https://gi$
7 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-eda28104/.git'
8 timing stage:rollbackFailedOptional Completed in 3ms
9 timing stage:runTopLevelLifecycles Completed in 1212ms
10 verbose stack Error: Command failed: git clone --mirror -q https://github.com/Samfox2/homebridge-doorbell.git /root/.npm/_cacache/tmp/git-c$
10 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-eda28104/.git'
10 verbose stack
10 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
10 verbose stack     at ChildProcess.emit (events.js:198:13)
10 verbose stack     at maybeClose (internal/child_process.js:982:16)
10 verbose stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
10 verbose stack     at Socket.emit (events.js:198:13)
10 verbose stack     at Pipe._handle.close (net.js:607:12)
11 verbose cwd /home/pi
12 verbose Linux 4.19.66-v7+
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "git+https://github.com/Samfox2/homebridge-doorbell.git"
14 verbose node v10.22.0
15 verbose npm  v6.14.8
16 error code 128
17 error Command failed: git clone --mirror -q https://github.com/Samfox2/homebridge-doorbell.git /root/.npm/_cacache/tmp/git-clone-eda28104/.$
17 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-eda28104/.git'
18 verbose exit [ 1, true ]

**Comment by toshibochan** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'git+https://github.com/Samfox2/homebridge-doorbell.git' ]
2 info using npm@6.14.8
3 info using node@v10.22.0
4 verbose npm-session 10df30da31b81568
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for git+https://github.com/Samfox2/homebridge-doorbell.git Command failed: git clone --mirror -q https://github.com/Samfox2/homebridge-doorbell.git /root/.npm/_cacache/tmp/git-clone-eda28104/.git
7 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-eda28104/.git'
8 timing stage:rollbackFailedOptional Completed in 3ms
9 timing stage:runTopLevelLifecycles Completed in 1212ms
10 verbose stack Error: Command failed: git clone --mirror -q https://github.com/Samfox2/homebridge-doorbell.git /root/.npm/_cacache/tmp/git-clone-eda28104/.git
10 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-eda28104/.git'
10 verbose stack
10 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
10 verbose stack     at ChildProcess.emit (events.js:198:13)
10 verbose stack     at maybeClose (internal/child_process.js:982:16)
10 verbose stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
10 verbose stack     at Socket.emit (events.js:198:13)
10 verbose stack     at Pipe._handle.close (net.js:607:12)
11 verbose cwd /home/pi
12 verbose Linux 4.19.66-v7+
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "git+https://github.com/Samfox2/homebridge-doorbell.git"
14 verbose node v10.22.0
15 verbose npm  v6.14.8
16 error code 128
17 error Command failed: git clone --mirror -q https://github.com/Samfox2/homebridge-doorbell.git /root/.npm/_cacache/tmp/git-clone-eda28104/.git
17 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-eda28104/.git'
18 verbose exit [ 1, true ]

**Comment by toshibochan** [comment]
if I don't use "sudo" it install but I don't know what folder it install. Is not in /usr/lib/node_modules where Homebridge is.
please help

**Comment by Samfox2** [comment]
The plugin does not work anymore. Since the API has changed doorbell service does not work without an attached camera. Please use https://github.com/Samfox2/homebridge-videodoorbell instead.
